Website buildup
mhamedGd/Capstone-Project-First pull request #1
Opened 2022-09-14 15:11 UTC by mhamedGd

- 2 pages are included (home, about).
- Fairly close to the provided design.
- A mobile-first approach that supports desktop monitors.
- Used the "Tailwind" framework for CSS, This was the first time I ever use Tailwind.
- All images used are either copy-right free or made by me.

2022-09-14 17:21 UTC, jasonfelice requested changes
Hi @mhamedGd, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

#Highlights 
No Linter Errors✔️ 
Great design ✔️

## Suggested changes
- [ ] Your current readme is empty. Please use the Miroverse readme template.

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-14 17:21 UTC, jasonfelice commented on src/script/mobile-menu
> +});
- [ ] The menu button is not working. It's because this code is not executing. Kindly fix that. 😄

2022-09-14 17:21 UTC, jasonfelice commented on public/output.css
> +.nav-menu {
- [ ] The header looks great. But according to the project requirements, please stick to the following design:

![image](https://user-images.githubusercontent.com/92215878/190219278-3d6877f0-7113-455e-9037-e25891c7d5a7.png)

2022-09-14 17:21 UTC, jasonfelice commented on index.html
> +    </section>
- [ ] Kindly add the following footer after the "partners" section.
_Do the same for the about page_

![image](https://user-images.githubusercontent.com/92215878/190219692-276a2cec-54c8-4bd0-bd3c-2ddc28e93835.png)

2022-09-14 17:21 UTC, jasonfelice commented on about.html
> +    </section>
- [ ] The about page is missing the following section. Kindly add this section to your about page. 😃 

![image](https://user-images.githubusercontent.com/92215878/190220106-160350fb-0d79-46d9-841d-0ec069cdf728.png)

2022-09-14 19:51 UTC, mhamedGd commented on src/script/mobile-menu
> +});
Weird, It is working for me, I even opened the website on my phone right now and it does work.

2022-09-14 19:52 UTC, mhamedGd commented on public/output.css
> +.nav-menu {
Alright thank you, I will.

2022-09-14 19:52 UTC, mhamedGd commented on about.html
> +    </section>
Oww I forgot about this one, Thank you I will.

2022-09-14 19:52 UTC, mhamedGd commented on index.html
> +    </section>
Oww yeas ofcourse, Thank you.

2022-09-14 19:54 UTC, mhamedGd commented on src/script/mobile-menu
> +});
Probably because this project uses Tailwind and you need to see the live demo to know if it worked
https://mhamedgd.github.io/Capstone-Project-First/

2022-09-15 11:24 UTC, Reem-lab approved these changes
# Hi @mhamedGd,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality and the design✅
📌 Good commit messages ✅
📌 Professional README ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 11:51 UTC, merged